### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by offa** [parmstrong842/WorkTracker#1]
How about submitting the project to [F-Droid](https://f-droid.org/)?

### Additional information

- [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/)
- [How to submit](https://f-droid.org/en/contribute/#submit-applications)

**Comment by offa** [comment]
ping @parmstrong842

**Comment by parmstrong842** [comment]
Thank you for your suggestion. I'm actually working on getting it submitted right now. It should be on there soon.

**Comment by offa** [comment]
Nice, thank you! :-)

**Comment by IzzySoft** [comment]
@parmstrong842 maybe you missed the ping (or the ping missed you): the MR [waits for your feedback](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12747#note_1353814539). Can you please chime in? Thanks!

**Comment by offa** [comment]
ping @parmstrong842

**Comment by IzzySoft** [comment]
Looks like @parmstrong842 went AWOL. Which most likely means the app is also unmaintained now. So we probably cannot include it with F-Droid – and I'll abandon my merge request soon if I cannot get it done…

**Comment by offa** [comment]
I'm closing here too.
